### ISSUE TITLE
text() is ok, but other methods with image, info, done, error  are crashed.

### ISSUE THREAD

**Issue by keyeMyria** [listenzz/react-native-hud-hybrid#3]
Method text() is ok, while methods with info info, done, error are creashed.

**Comment by listenzz** [comment]
Had you drag the ProgressHUD.bundle to your iOS project?

**Comment by keyeMyria** [comment]
no

**Comment by listenzz** [comment]
dowload 
[ProgressHUD.bundle.zip](https://github.com/listenzz/react-native-hud-hybrid/files/2145035/ProgressHUD.bundle.zip) 

unzip and drag it to your iOS project

**Comment by keyeMyria** [comment]
It's ok, Thanks a ton. More installation instructions, It's perfect.
