### ISSUE TITLE
ios release版本打包提示：Library not found for -lProgressHUD

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-hud-hybrid#6]
debug 正常，会是哪里设置有问题？

**Comment by yunuo-tech** [comment]
该做的都做了，Framework Search Paths也添加了路径，可还是不行

**Comment by yunuo-tech** [comment]
紧急求助~~ 现在就差这个问题了，解决完就能上架了

**Comment by listenzz** [comment]
是用 cocoapod 集成的吗？

在 build settings 中搜索下，找到然后删除

**Comment by listenzz** [comment]
lProgressHUD 可能是你之前使用的 HUD 的名字

**Comment by listenzz** [comment]
可能在 Other Linker Flags 中，也可能在 Search Paths 中，或其它搜索到的地方，找到，删除

**Comment by yunuo-tech** [comment]
不是用 cocoapod集成的，是直接 link 的，可是，居然在整个项目都搜索不到 lProgressHUD 这个字符。而且第一个字母是小写的 L，不是大写的 i

**Comment by yunuo-tech** [comment]
之前没有用过其他的 HUD

**Comment by yunuo-tech** [comment]
react-native unlink react-native-hud-hybrid 后正常了，可我还想用这个库。。。

**Comment by listenzz** [comment]
我看下 link 出了什么问题

**Comment by listenzz** [comment]
更新到 0.27.0

**Comment by yunuo-tech** [comment]
> 更新到 0.27.0

可以了，万分感谢！！
